/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop2finalproject;

import com.sun.glass.events.KeyEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Shinozaki-Kirishima
 */
public class GPAView extends javax.swing.JFrame {
    //field 
    private double currentGPA;
    //getters for individual fields 
    public String getEnterName()
    {
        return this.enterName.getText();
    }
    public String getEnterID()
    {
        return this.enterID.getText();
    }
    //setter for display 
    public void setDisplayArea(ArrayList<Object> studentInfo)
    {
        DefaultTableModel model=(DefaultTableModel)displayArea.getModel();
        //clear table content   
        model.setRowCount(0);
        //create object array
        Object[] row=new Object[5];
        //add ArrayList, studentInfo, elelment to the object array
        row[0]=studentInfo.get(0);
        row[1]=studentInfo.get(1);
        row[2]=studentInfo.get(2);
        row[3]=studentInfo.get(3);
        row[4]=studentInfo.get(4);
        //clear login fields
        this.enterID.setText("");
        this.enterName.setText("");
        this.addMark1.setText("");
        //add row to model and display to user 
        model.addRow(row);
        
    }
    //get the current gpa from jtable database
    public double getCurrentGPA()
    {
        //get the gpa value 
        String str=displayArea.getModel().getValueAt(0, 4).toString();
        this.currentGPA=Double.valueOf(str);
        return this.currentGPA;
    }
    public String getDatabaseUserName()
    {
        //get the user in the display
        String str=displayArea.getModel().getValueAt(0, 1).toString();
        return str;
    }
    public String getDatabaseID()
    {
        //get the user id in the display
        String str=displayArea.getModel().getValueAt(0, 2).toString();
        return str;
    }
    public double getAddMark1()
    {
        double additionalMark=Double.parseDouble(this.addMark1.getText());
        return additionalMark;
    }
    //add action listeners to each button
    /*If the calculate Button is clicked execute a method
      in the Controller named actionPerformed*/
    void addSearchListener(ActionListener listenForSearchButton)
    {
        this.search.addActionListener(listenForSearchButton);
    }
     /* If the Register Button is clicked execute a method
       in the Controller named actionPerformed*/
    void addRegisterListener(ActionListener listenForRegisterButton)
    {
        this.register.addActionListener(listenForRegisterButton);
    }
    /* If the Update Button is clicked execute a method
       in the Controller named actionPerformed*/
    void addUpdateListener(ActionListener listenForUpdateButton)
    {
       this.update.addActionListener(listenForUpdateButton);
    }
    /**
     * Creates new form Display
     */
    public GPAView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        UniqueLabel = new javax.swing.JTextField();
        NameLabel = new javax.swing.JTextField();
        enterID = new javax.swing.JPasswordField();
        ScrollPane = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        enterName = new javax.swing.JTextField();
        addMark1 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        additonalMarks = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        jPanel1.add(search);
        search.setBounds(20, 410, 190, 30);

        UniqueLabel.setEditable(false);
        UniqueLabel.setBackground(new java.awt.Color(0, 0, 0));
        UniqueLabel.setForeground(new java.awt.Color(255, 255, 255));
        UniqueLabel.setText("Enter Unique ID Below");
        UniqueLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniqueLabelActionPerformed(evt);
            }
        });
        jPanel1.add(UniqueLabel);
        UniqueLabel.setBounds(290, 30, 140, 30);

        NameLabel.setEditable(false);
        NameLabel.setBackground(new java.awt.Color(0, 0, 0));
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Enter Name Below");
        NameLabel.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(NameLabel);
        NameLabel.setBounds(30, 30, 120, 30);

        enterID.setBackground(new java.awt.Color(0, 0, 0));
        enterID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(enterID);
        enterID.setBounds(290, 80, 140, 30);

        ScrollPane.setBackground(new java.awt.Color(0, 0, 0));
        ScrollPane.setForeground(new java.awt.Color(255, 255, 255));

        displayArea.setBackground(new java.awt.Color(204, 255, 255));
        displayArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Unique_ID", "Grade", "GPA"
            }
        ));
        ScrollPane.setViewportView(displayArea);

        jPanel1.add(ScrollPane);
        ScrollPane.setBounds(20, 120, 453, 240);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 740, 10);

        enterName.setBackground(new java.awt.Color(0, 0, 0));
        enterName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(enterName);
        enterName.setBounds(30, 80, 130, 30);

        addMark1.setBackground(new java.awt.Color(0, 0, 0));
        addMark1.setForeground(new java.awt.Color(255, 255, 255));
        addMark1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addMark1KeyTyped(evt);
            }
        });
        jPanel1.add(addMark1);
        addMark1.setBounds(490, 120, 160, 19);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        jPanel1.add(update);
        update.setBounds(490, 410, 190, 30);

        additonalMarks.setEditable(false);
        additonalMarks.setBackground(new java.awt.Color(0, 0, 0));
        additonalMarks.setForeground(new java.awt.Color(255, 255, 255));
        additonalMarks.setText("Enter Additional Marks");
        jPanel1.add(additonalMarks);
        additonalMarks.setBounds(490, 79, 160, 30);

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.setToolTipText("");
        jPanel1.add(register);
        register.setBounds(260, 410, 190, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-220, -70, 1100, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UniqueLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniqueLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniqueLabelActionPerformed

    private void addMark1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addMark1KeyTyped
        // if any key except numerical keys are typed, consume them 
        char character=evt.getKeyChar();
        if(!(Character.isDigit(character)||(character==KeyEvent.VK_BACKSPACE)||(character==KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
            //make a pop up botification, notifying the user when an invalid character is entered
            final ImageIcon icon1 = new ImageIcon("Joptionpane/invalid.gif");
            JOptionPane.showMessageDialog(null, "", "Character Entered is Not Valid!",
            JOptionPane.INFORMATION_MESSAGE, icon1);
        }//if the character is backspaced, beep only 
        if((character==KeyEvent.VK_BACKSPACE)||(character==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_addMark1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPAView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPAView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPAView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPAView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPAView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameLabel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextField UniqueLabel;
    private javax.swing.JTextField addMark1;
    private javax.swing.JTextField additonalMarks;
    private javax.swing.JTable displayArea;
    private javax.swing.JPasswordField enterID;
    private javax.swing.JTextField enterName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton register;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
